language: ruby
rvm:
  - 2.4.1
before_install:
  - "if [ \"$TRAVIS_EVENT_TYPE\" != \"cron\" ] && echo \"$TRAVIS_COMMIT_MESSAGE\" | grep -F -q \"Auto-commit\"; then echo \"Last commit was made by Travis, exiting...\" && exit 0; fi"
install:
  - bundle install
script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      make deploy;
    else make build; fi

branches:
  only:
    - staging
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
sudo: false
cache: bundler
