before_install:
  - "if [ \"$TRAVIS_EVENT_TYPE\" != \"cron\" ] && echo \"$TRAVIS_COMMIT_MESSAGE\" | grep -F -q \"Auto-commit\"; then echo \"Last commit was made by Travis, exiting...\" && exit 0; fi"
  - rvm install 2.4.1
install:
  - bundle install
script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      make deploy;
    else make build; fi
