name: The News Panels
shortname: News Panels
description: "The news in comics."
icon: "/images/logo.png"

twitter: "@TheNewsPanels"
instagram: "thenewspanels"

url: "https://thenewspanels.com"
baseurl: "https://thenewspanels.com"
domainurl: "https://thenewspanels.com"
baseurl: "/"

source: "./"
destination: "./_site/"

positions:
  - - rowStart: 1
      colStart: 1
      rowEnd: 3
      colEnd: 9
    - rowStart: 3
      colStart: 1
      rowEnd: 5
      colEnd: 7
    - rowStart: 5
      colStart: 1
      rowEnd: 7
      colEnd: 7
    - rowStart: 7
      colStart: 1
      rowEnd: 10
      colEnd: 7
    - rowStart: 3
      colStart: 7
      rowEnd: 10
      colEnd: 9
    - rowStart: 10
      colStart: 1
      rowEnd: 12
      colEnd: 9
    - rowStart: 12
      colStart: 1
      rowEnd: 14
      colEnd: 5
    - rowStart: 12
      colStart: 5
      rowEnd: 14
      colEnd: 9
  - - rowStart: 1
      colStart: 1
      rowEnd: 5
      colEnd: 4
    - rowStart: 1
      colStart: 4
      rowEnd: 3
      colEnd: 9
    - rowStart: 3
      colStart: 4
      rowEnd: 5
      colEnd: 9
    - rowStart: 5
      colStart: 1
      rowEnd: 7
      colEnd: 9
    - rowStart: 7
      colStart: 1
      rowEnd: 9
      colEnd: 5
    - rowStart: 7
      colStart: 5
      rowEnd: 9
      colEnd: 9
    - rowStart: 9
      colStart: 1
      rowEnd: 11
      colEnd: 9
    - rowStart: 11
      colStart: 1
      rowEnd: 13
      colEnd: 6
    - rowStart: 13
      colStart: 1
      rowEnd: 15
      colEnd: 6
    - rowStart: 11
      colStart: 6
      rowEnd: 15
      colEnd: 9

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Makefile
  - .travis.yml
  - _conf*.yml
  - _algolia_api_key
  - .gitignore
  - .idea/
  - .sass-cache/
  - vendor/

sass:
    sass_dir: ./css

pwa:
    dest_js_directory: js

prismic:
    endpoint: "https://thenewspanels.prismic.io/api"
    links:
        Paper:
            permalink: /:uid/
        Comic:
            permalink: /comics/:uid/
    collections:
        papers:
            form: papers
            permalink: /:uid/
            layout: page.html
            page_size: 1000
            output: true
            output_limit: nil
        comics:
            form: comics
            permalink: /comics/:uid/
            layout: comic.html
            page_size: 10000
            output: true
            output_limit: nil

algolia:
    application_id: 'X2CM5LGGSE'
    index_name: 'prod_comics'
    settings:
        searchableAttributes:
          - unordered(page-title)
          - unordered(content)

gems:
  - jekyll-sitemap
  - jekyll-pwa-plugin
  - jekyll-algolia
  - jekyll-prismic
